language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '4'
after_success:
  - npm install -g travis-deploy-once semantic-release
  - travis-deploy-once "semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
